version: "3"

services:
  
    db:
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: app
        POSTGRES_PASSWORD: local-dev
        POSTGRES_DB: app
      # NOTE: Uncomment the following lines to persist a postgres data to a local volume.
      # volumes:
        # - "/custom/mount:/var/lib/postgresql/data"
      ports:
        - '5432:5432'